version: "3.7"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: db
    command: /server
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    links:
      - backend

  prediction:
    build: ./prediction/
    environment:
      DD_DB_HOST: db
    depends_on:
      - db
    networks:
      - evraz-network

  db:
    container_name: db
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: goland
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data:

networks:
  evraz-network:
    driver: bridge